[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/", "solmate/=node_modules/solmate/"]



remappings = ['@openzeppelin=lib/openzeppelin-contracts']

